<?php

use Illuminate\Database\Seeder;

class TeacherTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if(DB::table('teachers')->get()->count() == 0){

            DB::table('teachers')->insert([

                [
                    't_id' => '01181001',
                    'firstname' => 'James',
                    'middlename' => 'R',
                    'lastname' => 'Victoria',
                    'gender' => 'Male',
                    'email' => 'james@gmail.com',
                    'password' => bcrypt('01181001'),
                    'birthday' => date('Y-m-d H:i:s'),
                    'address1' => 'dummy',
                    'address2' => 'dummy',
                    'contact' => '09123456789',
                    'barangay' => 'dummy',
                    'religion' => 'dummy',
                    'municipality' => 'dummy',
                    'province' => 'dummy',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    't_id' => '01181002',
                    'firstname' => 'Paulo',
                    'middlename' => 'R',
                    'lastname' => 'Dela Pena',
                    'gender' => 'Male',
                    'email' => 'paulo@gmail.com',
                    'password' => bcrypt('01181002'),
                    'birthday' => date('Y-m-d H:i:s'),
                    'address1' => 'dummy',
                    'address2' => 'dummy',
                    'contact' => '09123456789',
                    'barangay' => 'dummy',
                    'religion' => 'dummy',
                    'municipality' => 'dummy',
                    'province' => 'dummy',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    't_id' => '01181003',
                    'firstname' => 'Jared',
                    'middlename' => 'R',
                    'lastname' => 'Del Rosario',
                    'gender' => 'Male',
                    'email' => 'jared@gmail.com',
                    'password' => bcrypt('01181003'),
                    'birthday' => date('Y-m-d H:i:s'),
                    'address1' => 'dummy',
                    'address2' => 'dummy',
                    'contact' => '09123456789',
                    'barangay' => 'dummy',
                    'religion' => 'dummy',
                    'municipality' => 'dummy',
                    'province' => 'dummy',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    't_id' => '01181004',
                    'firstname' => 'Jake',
                    'middlename' => 'R',
                    'lastname' => 'Libot',
                    'gender' => 'Male',
                    'email' => 'jake@gmail.com',
                    'password' => bcrypt('01181004'),
                    'birthday' => date('Y-m-d H:i:s'),
                    'address1' => 'dummy',
                    'address2' => 'dummy',
                    'contact' => '09123456789',
                    'barangay' => 'dummy',
                    'religion' => 'dummy',
                    'municipality' => 'dummy',
                    'province' => 'dummy',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    't_id' => '01181005',
                    'firstname' => 'Kennet',
                    'middlename' => 'R',
                    'lastname' => 'Kabinet',
                    'gender' => 'Male',
                    'email' => 'kennet@gmail.com',
                    'password' => bcrypt('01181005'),
                    'birthday' => date('Y-m-d H:i:s'),
                    'address1' => 'dummy',
                    'address2' => 'dummy',
                    'contact' => '09123456789',
                    'barangay' => 'dummy',
                    'religion' => 'dummy',
                    'municipality' => 'dummy',
                    'province' => 'dummy',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    't_id' => '01181006',
                    'firstname' => 'Cleo',
                    'middlename' => 'R',
                    'lastname' => 'Tanglao',
                    'gender' => 'Male',
                    'email' => 'cleo@gmail.com',
                    'password' => bcrypt('01181006'),
                    'birthday' => date('Y-m-d H:i:s'),
                    'address1' => 'dummy',
                    'address2' => 'dummy',
                    'contact' => '09123456789',
                    'barangay' => 'dummy',
                    'religion' => 'dummy',
                    'municipality' => 'dummy',
                    'province' => 'dummy',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    't_id' => '01181007',
                    'firstname' => 'Gerald',
                    'middlename' => 'R',
                    'lastname' => 'Pangan',
                    'gender' => 'Female',
                    'email' => 'angel@gmail.com',
                    'password' => bcrypt('01181007'),
                    'birthday' => date('Y-m-d H:i:s'),
                    'address1' => 'dummy',
                    'address2' => 'dummy',
                    'contact' => '09123456789',
                    'barangay' => 'dummy',
                    'religion' => 'dummy',
                    'municipality' => 'dummy',
                    'province' => 'dummy',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    't_id' => '01181008',
                    'firstname' => 'Jonald',
                    'middlename' => 'R',
                    'lastname' => 'Donald',
                    'gender' => 'Male',
                    'email' => 'jonald@gmail.com',
                    'password' => bcrypt('01181008'),
                    'birthday' => date('Y-m-d H:i:s'),
                    'address1' => 'dummy',
                    'address2' => 'dummy',
                    'contact' => '09123456789',
                    'barangay' => 'dummy',
                    'religion' => 'dummy',
                    'municipality' => 'dummy',
                    'province' => 'dummy',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    't_id' => '01181009',
                    'firstname' => 'Adrian',
                    'middlename' => 'R',
                    'lastname' => 'De Guzman',
                    'gender' => 'Male',
                    'email' => 'adrian@gmail.com',
                    'password' => bcrypt('01181009'),
                    'birthday' => date('Y-m-d H:i:s'),
                    'address1' => 'dummy',
                    'address2' => 'dummy',
                    'contact' => '09123456789',
                    'barangay' => 'dummy',
                    'religion' => 'dummy',
                    'municipality' => 'dummy',
                    'province' => 'dummy',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    't_id' => '011810010',
                    'firstname' => 'Renzo',
                    'middlename' => 'R',
                    'lastname' => 'Candelaria',
                    'gender' => 'Male',
                    'email' => 'renzo@gmail.com',
                    'password' => bcrypt('011810010'),
                    'birthday' => date('Y-m-d H:i:s'),
                    'address1' => 'dummy',
                    'address2' => 'dummy',
                    'contact' => '09123456789',
                    'barangay' => 'dummy',
                    'religion' => 'dummy',
                    'municipality' => 'dummy',
                    'province' => 'dummy',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    't_id' => '011810011',
                    'firstname' => 'Paul',
                    'middlename' => 'R',
                    'lastname' => 'Cabrera',
                    'gender' => 'Male',
                    'email' => 'paul@gmail.com',
                    'password' => bcrypt('011810011'),
                    'birthday' => date('Y-m-d H:i:s'),
                    'address1' => 'dummy',
                    'address2' => 'dummy',
                    'contact' => '09123456789',
                    'barangay' => 'dummy',
                    'religion' => 'dummy',
                    'municipality' => 'dummy',
                    'province' => 'dummy',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    't_id' => '011810012',
                    'firstname' => 'Arjay',
                    'middlename' => 'R',
                    'lastname' => 'Kyros',
                    'gender' => 'Male',
                    'email' => 'arjay@gmail.com',
                    'password' => bcrypt('011810012'),
                    'birthday' => date('Y-m-d H:i:s'),
                    'address1' => 'dummy',
                    'address2' => 'dummy',
                    'contact' => '09123456789',
                    'barangay' => 'dummy',
                    'religion' => 'dummy',
                    'municipality' => 'dummy',
                    'province' => 'dummy',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    't_id' => '011810013',
                    'firstname' => 'Warren',
                    'middlename' => 'R',
                    'lastname' => 'Fernandez',
                    'gender' => 'Male',
                    'email' => 'adrian@gmail.com',
                    'password' => bcrypt('011810013'),
                    'birthday' => date('Y-m-d H:i:s'),
                    'address1' => 'dummy',
                    'address2' => 'dummy',
                    'contact' => '09123456789',
                    'barangay' => 'dummy',
                    'religion' => 'dummy',
                    'municipality' => 'dummy',
                    'province' => 'dummy',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    't_id' => '011810014',
                    'firstname' => 'Revie',
                    'middlename' => 'R',
                    'lastname' => 'Regala',
                    'gender' => 'Male',
                    'email' => 'adrian@gmail.com',
                    'password' => bcrypt('011810014'),
                    'birthday' => date('Y-m-d H:i:s'),
                    'address1' => 'dummy',
                    'address2' => 'dummy',
                    'contact' => '09123456789',
                    'barangay' => 'dummy',
                    'religion' => 'dummy',
                    'municipality' => 'dummy',
                    'province' => 'dummy',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    't_id' => '011810015',
                    'firstname' => 'Jimboy',
                    'middlename' => 'R',
                    'lastname' => 'Regala',
                    'gender' => 'Male',
                    'email' => 'adrian@gmail.com',
                    'password' => bcrypt('011810015'),
                    'birthday' => date('Y-m-d H:i:s'),
                    'address1' => 'dummy',
                    'address2' => 'dummy',
                    'contact' => '09123456789',
                    'barangay' => 'dummy',
                    'religion' => 'dummy',
                    'municipality' => 'dummy',
                    'province' => 'dummy',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],
                [
                    't_id' => '011810016',
                    'firstname' => 'Surerus',
                    'middlename' => 'R',
                    'lastname' => 'De Guzman',
                    'gender' => 'Male',
                    'email' => 'surerus@gmail.com',
                    'password' => bcrypt('011810016'),
                    'birthday' => date('Y-m-d H:i:s'),
                    'address1' => 'dummy',
                    'address2' => 'dummy',
                    'contact' => '09123456789',
                    'barangay' => 'dummy',
                    'religion' => 'dummy',
                    'municipality' => 'dummy',
                    'province' => 'dummy',
                    'created_at' => date('Y-m-d H:i:s'),
                    'updated_at' => date('Y-m-d H:i:s'),
                ],

            ]);

        }
    }
}
